# words
[[word]]
pattern = "f[u*]-ck" # 'fuck' and similar

[[word]]
pattern = "homo"

[[word]]
pattern = "g[a4]y" # 'gay' and similar

[[word]]
pattern = "f[a4]g" # 'fag' and similar

[[word]]
pattern = "sh[i1*]t" # 'shit' and similar

[[word]]
pattern = "b[i1*]tch" # 'bitch' and similar

[[word]]
pattern = "asshole" # 'asshole' and similar

# names
[[name]]
pattern = "hitler"

[[name]]
pattern = "osama"
